INSERT INTO `genero_cinematografico` 
VALUES 
(1,'Ação'),
(2,'Aventura'),
(3,'Cinema de arte'),
(4,'Chanchada'),
(5,'Cinema catástrofe'),
(6,'Comédia'),
(7,'Comédia romântica'),
(8,'Comédia dramática'),
(9,'Comédia de ação'),
(10,'Dança'),
(11,'Documentário'),
(12,'Docuficção'),
(13,'Drama'),
(14,'Espionagem'),
(15,'Faroeste'),
(16,'Fantasia científica'),
(17,'Ficção científica'),
(18,'Filmes de guerra'),
(19,'Musical'),
(20,'Filme policial'),
(21,'Romance'),
(22,'Seriado'),
(23,'Suspense'),
(24,'Terror');